# Makefile A1
# by Eva M. Sehr

CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra

all: fibo_eff fibo_ineff

fibo_eff: evasehr-fibo_efficient.cpp
	g++ -o fibo_eff  evasehr-fibo_efficient.cpp

fibo_ineff: evasehr-fibo_inefficient.cpp
	g++ -o fibo_ineff evasehr-fibo_inefficient.cpp
